
language: python

python:
  - "3.5.2"

before_script:
  - createdb diarydb;

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov=app/
after_success:
  - coveralls

cache: pip
