language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database diarydb;' -U postgres
env:
  - export SECRET_KEY="!@#(#_jjdril^&@efr8599"
  - export FLASK_CONFIG="testing"
  - export DB_HOST="localhost"
  - export DB_NAME="diarydb"
  - export DB_USERNAME="chariss"
  - export DB_PASSWORD="pooler32"
  - export JWT_SECRET_KEY="(#_jjdril^&@e"
script:
  - pytest --cov=tests/
after_success:
  - coveralls
